### ISSUE TITLE
「最新のお知らせ」の表示を見やすくしたい

### ISSUE THREAD

**Issue by ta14-u** [codeforkumamoto/covid19#109]
## 改善詳細 / Details of Improvement
「最新のお知らせ」は以下の表示の方がより見やすくなると思います。
- お知らせを日付の降順で表示する
- 日付の表示フォーマットを yyyy/mm/dd で表示する

## スクリーンショット / Screenshot
<img width="500" alt="スクリーンショット 2020-03-26 20 34 06" src="https://user-images.githubusercontent.com/57866052/77643162-36067780-6fa2-11ea-8911-8a3ad7de2ad3.png">
<img width="500" alt="スクリーンショット 2020-03-26 21 04 59" src="https://user-images.githubusercontent.com/57866052/77645192-abc01280-6fa5-11ea-96d2-8dc94d21dc69.png">

## 期待する見せ方・挙動 / Expected behavior
- お知らせを日付の降順で表示
- 日付の表示フォーマットを yyyy/mm/dd で表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ta14-u** [comment]
やってみます

**Comment by makoragi** [comment]
そうですね、良いと思います！
