### ISSUE TITLE
検査陽性者の状況(仮データ)の入院中の内訳追加

### ISSUE THREAD

**Issue by kanasan3** [codeforkumamoto/covid19#124]
## 改善詳細 / Details of Improvement
- 検査陽性者の状況(仮データ)の入院中の内訳に「不明」を追加したい。
- 自治体からの新規検査陽性者の情報では容態が明示されておらず、
　軽症・中等症or重症のどちらにも分類できないため。

## 期待する見せ方・挙動 / Expected behavior
- 検査陽性者の状況(仮データ)の入院中の内訳案
　「軽症・中等症」「重症」に加えて「不明」もしくは「情報提供なし」

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by makoragi** [comment]
状況不明な陽性者数を無理に入れるより、状況が分かってから陽性者数を入れるようにします。

速報を拾ってデータを更新していたら、自動化やオープンデータ化したときに困る（対応できないor対応が困難）ため。
