### ISSUE TITLE
他地域の対策サイト一覧リンクを置く

### ISSUE THREAD

**Issue by makoragi** [codeforkumamoto/covid19#132]
## 起こっている問題 / The Problem
- タイトル通り。九州総合通信局から紹介してもらったリンクを張る。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/5866690/78201553-da217e80-74cc-11ea-96bd-d88c83634177.png)

## 期待する見せ方・挙動 / Expected Behavior
- スクリーンショットの通り
![image](https://user-images.githubusercontent.com/5866690/78201477-a0e90e80-74cc-11ea-8699-fcf76fd97793.png)

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaito25atugich** [comment]
やりたいです！

**Comment by makoragi** [comment]
@kaito25atugich どうもありがとうございました！

興味がありましたら下記Facebookグループへのご参加もどうぞ！
https://www.facebook.com/groups/CodeForKumamoto
