### ISSUE TITLE
カードのOGP画像が機能してない

### ISSUE THREAD

**Issue by makoragi** [codeforkumamoto/covid19#157]
## 起こっている問題 / The Problem
- カードを表示してSNSシェアすると、そのときの情報（グラフなど）が画像になる、はず。
- ただしメインのOGP画像のまま。
- 至る所で見かける「東京都の画像になってしまっている」ではないので、緊急性は低い

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/5866690/79072107-392b9280-7d1a-11ea-849c-04b0cbe5af85.png)

## 期待する見せ方・挙動 / Expected Behavior
- 東京都と同じく、現在の情報を画像として使う

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fkumamoto.stopcovid19.jp%2Fcards%2Fdetails-of-confirmed-cases%2F

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaito25atugich** [comment]
nuxt.config.ts内でfb:app_idを設定し、pages/cards/_card.vueの一部を熊本のものに変更してもなおらないのでしょうか。

**Comment by makoragi** [comment]
@kaito25atugich ありがとうございます。ちょっと調べてみます。Issueとしてあげただけで対応していないため。

**Comment by makoragi** [comment]
本家マージのときに改善していてIssue Close忘れ
