### ISSUE TITLE
熊本県のサイトへのリンクについて

### ISSUE THREAD

**Issue by UedaKezi** [codeforkumamoto/covid19#58]
## 改善詳細 / Details of Improvement
- この対策サイトと熊本県のサイトの情報の発信源（責任）が違うことの明確化

## スクリーンショット / Screenshot
バグではありません。左のボックス内の熊本県サイトへのリンク。

## 期待する見せ方・挙動 / Expected behavior
＜現在＞
◎新型コロナウイルス感染症が心配なとき
￥お子様をお持ちの皆様へ
oo県民の皆様へ
□事業者の皆様へ
・知事からのメッセージ
・当サイトについて
・熊本県公式ホームページ

＜変更（案）＞
・【県】熊本県公式ホームページ
◎【県】新型コロナウイルス感染症が心配なとき
￥【県】お子様をお持ちの皆様へ
oo【県】県民の皆様へ
□【県】事業者の皆様へ
・【県】知事からのメッセージ
・当サイトについて

ーーーー
当サイトについてのページで、
＜現在＞
「当サイトは新型コロナウイルス感染症 (COVID-19) に関する最新情報を提供するために、熊本県有志が開設したものです。」
　↓
＜変更（案）＞
「当サイトは新型コロナウイルス感染症 (COVID-19) に関する最新情報を提供するために、熊本県有志が開設したものです。熊本県から発表された情報を用いていますが、本サイトの運営に関しては熊本県は一切関係しておりません。」

## 動作環境・ブラウザ / Environment
- すべての動作環境

**Comment by makoragi** [comment]
@UedaKezi ありがとうございます！それでいきましょう！対応します！

**Comment by UedaKezi** [comment]
ありがとうございます。既に公開されている他の地域のサイトには、そういう表記はなかったので、逆に熊本恥ずかしい感じもしますが。。

**Comment by UedaKezi** [comment]
急ぎの対応、ありがとうございます！！！

熊本県情報政策課にもこれで公開して良いか、最終確認しますね。
あと、今後のデータがもらえるかも。。
