### ISSUE TITLE
TOPの最終更新日付と最新のお知らせの日付があってない

### ISSUE THREAD

**Issue by shota-yano** [codeforkumamoto/covid19#68]
## 起こっている問題 / The Problem
- サイトトップの最終更新日付と最新のお知らせの日付があっていない

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/44024424/76927702-124c8d00-6923-11ea-8db0-870f3d2c3dd4.png)

## 期待する見せ方・挙動 / Expected Behavior
- 最終更新が最新のお知らせと同じ日付か、最新のお知らせより新しいほうが良い(データだけ更新した時は最新のお知らせの日付より新しくなるイメージ)

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトトップにアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by makoragi** [comment]
本日分のデータ更新する際に対応します！

**Comment by makoragi** [comment]
更新しました。手動での修正だとミスりそう。
