### ISSUE TITLE
最新のお知らせが改行されている

### ISSUE THREAD

**Issue by shota-yano** [codeforkumamoto/covid19#70]
## 起こっている問題 / The Problem
- 最新のお知らせが途中で改行されている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/44024424/76928194-1e851a00-6924-11ea-983c-05485ef85f2a.png)

## 期待する見せ方・挙動 / Expected Behavior
- 改行されずに1行で表示する

## 起こっている問題の再現手段 / Steps to Reproduce
1. Chromeでサイトにアクセスする（Edge、IEは問題なく見える)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by makoragi** [comment]
これEdgeだとちゃんと表示されるんですが、なぜだろう。

**Comment by shota-yano** [comment]
vue初めて触ったんでどこで定義してるか追いきれてないですが、
幅と高さが指定してあるんですよね（東京のを見るとauto*auto)になってたので、そのあたりかなーとは思ってます・・・
![image](https://user-images.githubusercontent.com/44024424/76930079-02d04280-6929-11ea-8f77-6708638bf5a3.png)


↓東京
![image](https://user-images.githubusercontent.com/44024424/76929979-c7357880-6928-11ea-97d1-12f416cf69ad.png)

**Comment by shota-yano** [comment]
パット見た限りですが、WhatsNew.vueの.WhatsNew .WhatsNew-listクラスを修正すればよさそうです
`display: inline-flex;`
↓
`display: inline-block;`
※ほんとにこれでいいかは後で見てみます
