### ISSUE TITLE
あまびえ画像つくりました。

### ISSUE THREAD

**Issue by yamazakiharuki** [codeforkumamoto/covid19#74]
## 改善詳細
あまびえ画像作りました。
https://www.dropbox.com/s/1f5kl1ru7ozap3f/covid19_kumamoto_amabie_.png?dl=0

**Comment by yamazakiharuki** [comment]
県の色を赤にしたバージョンも一応置いておきます。
https://www.dropbox.com/s/jf0rgjs9vzpnj4i/covid19_kumamoto_amabie_red.png?dl=0

**Comment by makoragi** [comment]
こっちがいいですね！
熊本県の赤は「海老茶色」なので、それっぽい。

エビ！
