### ISSUE TITLE
小さいスマホだとヘッダが画面占有してしまう

### ISSUE THREAD

**Issue by makoragi** [codeforkumamoto/covid19#91]
スマホから投稿なので詳細は後で

**Comment by kanasan3** [comment]
こんな感じに見えています。スマホからなのですがうまく見えますでしょうか。
![B2B8ED84-5B48-43AD-BD59-783692DE8E40](https://user-images.githubusercontent.com/62243544/77029790-070b6700-69e0-11ea-9dec-0e622b531435.png)

**Comment by shota-yano** [comment]
福岡みたいに文字を上にして少しスペースあけるか、画像を表示サイズに合わせてリサイズですかね？
![image](https://user-images.githubusercontent.com/44024424/77044354-9fb2de80-6a02-11ea-8ce2-70f8773904fa.png)

**Comment by makoragi** [comment]
とりあえず画像の作り替えを考えてます
